# Generated by Django 5.2.4 on 2025-07-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('russian', models.CharField(blank=True, max_length=50, null=True)),
                ('kind', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('relation_kind', models.CharField(choices=[('prequel', 'Предыстория'), ('sequel', 'Продолжение'), ('adaptation', 'Адаптация'), ('other', 'Другое')], max_length=20)),
                ('relation_text', models.CharField(blank=True, max_length=100, null=True)),
                ('anime_id', models.CharField(blank=True, max_length=20, null=True)),
                ('anime_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manga_id', models.CharField(blank=True, max_length=20, null=True)),
                ('manga_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=500)),
                ('x332_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mal_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('russian', models.CharField(blank=True, max_length=255, null=True)),
                ('license_name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('english', models.CharField(blank=True, max_length=255, null=True)),
                ('japanese', models.CharField(blank=True, max_length=255, null=True)),
                ('kind', models.CharField(choices=[('tv', 'TV Сериал'), ('movie', 'Фильм'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'Спешл')], max_length=20)),
                ('rating', models.CharField(blank=True, choices=[('g', 'G'), ('pg', 'PG'), ('pg_13', 'PG-13'), ('r', 'R-17'), ('r_plus', 'R+'), ('rx', 'Rx')], max_length=10, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('anons', 'Анонсировано'), ('ongoing', 'Выходит'), ('released', 'Завершено')], max_length=20)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('episodes_aired', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Длительность в минутах', null=True)),
                ('url', models.URLField(max_length=500)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('next_episode_at', models.DateTimeField(blank=True, null=True)),
                ('is_censored', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, null=True)),
                ('description_source', models.TextField(blank=True, null=True)),
                ('aired_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_aired_on', to='anime.datemodel')),
                ('released_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_released_on', to='anime.datemodel')),
                ('genres', models.ManyToManyField(to='anime.genre')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anime.poster')),
                ('related', models.ManyToManyField(to='anime.related')),
                ('score_stats', models.ManyToManyField(to='anime.scorestat')),
                ('screenshots', models.ManyToManyField(to='anime.screenshot')),
                ('studios', models.ManyToManyField(to='anime.studio')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
