# Generated by Django 5.2.4 on 2025-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='anime_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='current_episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='current_translator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='participants_count',
            field=models.IntegerField(default=1),
        ),
    ]
