# Generated by Django 5.2.4 on 2025-07-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_room_anime_title_room_current_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
