# Generated by Django 5.2.4 on 2025-07-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_room_current_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='stream_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
