# Generated by Django 5.2.4 on 2025-08-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_room_stream_url_alter_room_participants_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='stream_url',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
    ]
