# Generated by Django 5.2.4 on 2025-08-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_room_stream_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='stream_url',
            field=models.JSONField(blank=True, default=list, max_length=500, null=True),
        ),
    ]
